name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger this workflow when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          # key: ${{ secrets.KEY }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/danr/projects/satrap-admin  # Replace with the path to your project on the server
            git pull origin main
            docker compose up -d --build
